In [2]:
!pip install numpy

In [3]:
import numpy as np

In [6]:
arr=np.array([[65,4,6,54,654,65,46,546,54,65,46,546,54,654,65,465,46,54,654,654]],np.int64)

In [7]:
arr.shape

(1, 20)

In [8]:
arr.dtype

dtype('int64')

In [10]:
arr[0,3]=69

In [11]:
arr[0,3]

np.int64(69)

## there are 5 types of method to create a numpy array

# 1. conversion for other python structures

In [15]:
listarr=np.array([[54,654,65,5],[654,564,654,654],[654,654,654,654],[654,56498,7,321]])

In [13]:
listarr.shape

(4, 4)

In [20]:
listarr.size

16

In [23]:
np.array({654,84,684,64,5,4}) ## set makes object, using the int and float architechture will be most suitable


array({64, 4, 5, 84, 684, 654}, dtype=object)

##2.intrinsic numpy array creation object

In [24]:
z=np.zeros((6,9))

In [25]:
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
rng=np.arange(15)
rng
rng.dtype

dtype('int64')

In [30]:
lspace =np.linspace(1,15,10) ## will provide 10 equally spaced values between 1 to 15
lspace

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

In [36]:
emp=np.empty((2,3))
emp## generate with random numbers

array([[5.68292349e-316, 0.00000000e+000, 6.68530621e-310],
       [6.68530622e-310, 5.75699520e-317, 5.75600311e-317]])

In [40]:
idt=np.identity(3)# 3x3 identity matrix
idt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
a=np.arange(99)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [71]:
a=a.reshape(3,33)# only if the distribution is valid , ig. here 3x33 =99 , so we can reshape this
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [72]:
a=a.ravel()
a           # to make this an 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [73]:
a2=np.array([[2,4,6],
             [5,4,6],
             [6,9,7]])

In [75]:
a2.sum(axis=0) ## sum of columns

array([13, 17, 19])

In [76]:
a2.sum(axis=1) ## sum of rows

array([12, 15, 22])

In [77]:
a2.T ##transpose

array([[2, 5, 6],
       [4, 4, 9],
       [6, 6, 7]])

In [79]:
for _ in a2.flat: ##gives an iterator
  print(_)

2
4
6
5
4
6
6
9
7


In [81]:
a2.ndim # show the dimention

2

In [82]:
a2.size # FOR SIZE

9

In [83]:
a2.nbytes # total bytes consumed

72

In [84]:
oo=np.array([54,34,545,34,54,2])

In [85]:
oo.argmax() # index of maximum value

np.int64(2)

In [86]:
oo.argmin() #index of minimum value

np.int64(5)

In [89]:
oo.argsort() # sorting the index

array([5, 1, 3, 0, 4, 2])

In [90]:
a2.argmax(axis=0)

array([2, 2, 2])

In [92]:
a2.argmin(axis=1)

array([0, 1, 0])

In [94]:
ar2=np.array([[23,5,6],
             [2,64,6],
             [4,7,5]])

In [98]:
a2+ar2## normal matrix calculations made easy

array([[25,  9, 12],
       [ 7, 68, 12],
       [10, 16, 12]])

In [101]:
np.where(a2>2)

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))

In [102]:
np.count_nonzero(a2)

9

In [107]:
temp=a2.tolist()
temp

[[2, 4, 6], [5, 4, 6], [6, 9, 7]]

###some examples

In [108]:
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])

#Solution

arr = np.arange(10)

arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [109]:
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Solution

arr = np.arange(10)

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
# Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution

arr = np.arange(10)

out = arr.copy()

out[out%2 == 1] = -1

print('Modified Array')
out

print('\nOriginal Array')
arr

In [110]:
# Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

# output: array([[0, 1, 2, 3, 4],
#                [5, 6, 7, 8, 9],
#                [1, 1, 1, 1, 1],
#                [1, 1, 1, 1, 1]])

# Solution

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [111]:
# Question: Stack the arrays a and b horizontally.

# Input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# Output: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#                [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])


# Solution:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [112]:
# Question: Get the positions where elements of a and b match

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: (array([1, 3, 5, 7]),)


# Solution

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [113]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)


# Solution

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [114]:
# Question: Reverse the rows of a 2D array arr.

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')
arr

# Solution

print("\nModified array")
arr[::-1, :]

Original array

Modified array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])